#!/usr/bin/env python3
"""Emit the ducks as SVG for the support site.

Reads the same generated Swift table the app compiles against, so the duck on
the website cannot drift from the duck in the app. Run it after `duck_forge.py
swift`, never instead of it — this file only ever reads.

    python3 tools/duck_svg.py            # rewrite docs/ducks/*.svg

Pixels become <rect>s, merged along each row so a solid belly is one rect
rather than fourteen. That keeps the files small enough to serve uncompressed
and crisp at any size, which a scaled-up PNG would not be.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, "Shared", "DuckStyles+Generated.swift")
OUT = os.path.join(ROOT, "docs", "ducks")

# The ducks the support page's strip shows, in order. A subset on purpose: that
# page is an invitation, not the catalogue.
FEATURED = ["classic", "blossom", "arcane", "reef", "ember", "cosmos"]

# Every style is emitted regardless, because the shared-countdown page has to be
# able to draw whichever duck turns up in a link.

# Same mapping as DuckStyle.color(for:) in Shared/DuckStyle.swift. Two of these
# are fixed rather than per-style, exactly as they are there.
#
# "g" is deliberately absent. It is the duck's reflection in the water, and it
# only makes sense with a pond under it — on the website there is none, so those
# pixels would read as a blue bar the duck is hovering over. Dropping the token
# leaves them transparent.
FIXED = {"k": "#17171A", "w": "#FFFFFF"}
FIELDS = {
    "b": "body", "s": "shade", "h": "light", "r": "beak", "e": "beakDark",
    "p": "cheek", "a": "accent", "d": "accentDark",
}


def parse_styles(text):
    """Pull every DuckStyle literal out of the generated table."""
    styles = {}
    for block in text.split("DuckStyle(")[1:]:
        ident = re.search(r'id:\s*"([^"]+)"', block)
        rows = re.search(r"rows:\s*\[(.*?)\]", block, re.S)
        if not ident or not rows:
            continue
        colors = {k: v for k, v in re.findall(r"(\w+):\s*0x([0-9A-Fa-f]{6})", block)}
        styles[ident.group(1)] = {
            "name": re.search(r'name:\s*"([^"]+)"', block).group(1),
            "colors": colors,
            "rows": re.findall(r'"([^"]*)"', rows.group(1)),
            "font": re.search(r"font:\s*\.(\w+)", block).group(1),
            "upper": re.search(r"uppercaseCaption:\s*(\w+)", block).group(1) == "true",
            "night": re.search(r"night:\s*(\w+)", block).group(1) == "true",
        }
    return styles


def svg(style):
    """One <rect> per run of identical pixels, walking each row left to right."""
    palette = dict(FIXED)
    for token, field in FIELDS.items():
        if field in style["colors"]:
            palette[token] = "#" + style["colors"][field].upper()

    rows = style["rows"]
    width = max(len(r) for r in rows)
    parts = []
    for y, line in enumerate(rows):
        x = 0
        while x < len(line):
            fill = palette.get(line[x])
            if fill is None:
                x += 1
                continue
            run = 1
            while x + run < len(line) and line[x + run] == line[x]:
                run += 1
            parts.append(
                f'<rect x="{x}" y="{y}" width="{run}" height="1" fill="{fill}"/>'
            )
            x += run

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {len(rows)}" '
        f'shape-rendering="crispEdges" role="img" '
        f'aria-label="{style["name"]}, a pixel-art rubber duck">'
        + "".join(parts)
        + "</svg>\n"
    )


def skies(styles):
    """Each duck's own sky, as a class the card sets its gradient from.

    Generated rather than hand-written for the same reason the sprites are:
    a duck on somebody else's sky is wrong, and hand-copied hex drifts.
    """
    lines = [
        "/* Generated by tools/duck_svg.py — do not edit.",
        "   One sky per duck, taken from the same table the app compiles. */",
        "",
    ]
    for ident in sorted(styles):
        colors = styles[ident]["colors"]
        lines.append(
            f'.sky-{ident} {{ --sky-top: #{colors["bgTop"].upper()};'
            f' --sky-bottom: #{colors["bgBottom"].upper()}; }}'
        )
    return "\n".join(lines) + "\n"


def metadata(styles):
    """What the shared-countdown page needs to draw a scene faithfully.

    Emitted rather than hand-copied for the same reason as the skies: the page
    has to agree with the app about what a duck looks like, and hex typed twice
    drifts. Only the fields the page actually renders.
    """
    return {
        ident: {
            "name": s["name"],
            "ink": "#" + s["colors"]["ink"].upper(),
            "skyTop": "#" + s["colors"]["bgTop"].upper(),
            "skyBottom": "#" + s["colors"]["bgBottom"].upper(),
            "water": "#" + s["colors"]["water"].upper(),
            "waterDeep": "#" + s["colors"]["waterDeep"].upper(),
            "font": s["font"],
            "upper": s["upper"],
        }
        for ident, s in sorted(styles.items())
    }


def main():
    with open(TABLE, encoding="utf-8") as handle:
        styles = parse_styles(handle.read())

    missing = [i for i in FEATURED if i not in styles]
    if missing:
        sys.exit(f"no such style in {TABLE}: {', '.join(missing)}")

    os.makedirs(OUT, exist_ok=True)
    for ident in styles:
        path = os.path.join(OUT, ident + ".svg")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(svg(styles[ident]))
        print(f"{os.path.relpath(path, ROOT)}  {styles[ident]['name']}")

    path = os.path.join(OUT, "skies.css")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(skies(styles))
    print(f"{os.path.relpath(path, ROOT)}  {len(styles)} skies")

    path = os.path.join(OUT, "styles.json")
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(metadata(styles), handle, indent=1, sort_keys=True)
    print(f"{os.path.relpath(path, ROOT)}  {len(styles)} styles")


if __name__ == "__main__":
    main()
